#!/bin/bash
#
# dmenu-edit: Use dmenu to open vim in a project folder 
# (and optionally start nailgun for clojure projects)
#
# Copyright 2012 Justin Steward <http://www.justinsteward.com/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# Global variables:
FILES="$HOME/PROJECTS"
BASE="$(dirname "$(readlink -f "$0")")"
. "$HOME/.dmenurc"

choice="$(tty -s && ls $FILES | $DMENU)"
if [[ $choice ]]; then
    cd $FILES/$choice
    if [ -f "project.clj" ]; then
        exec gnome-terminal -e "screen -c $HOME/.screenrc.vimclojure"
    else
        exec gnome-terminal -e "screen vim"
    fi
fi
