#!/bin/bash
#
# dmenu-netcfg: Switch netcfg network profiles.
#
# Copyright 2010 Tom Vincent <http://www.tlvince.com/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Depends:
# * netcfg

# Global variables:
CANONICAL="$(readlink -f "$0")"     # Handle symlinks
BASE="$(dirname "$CANONICAL")"

# Imports:
. "$HOME/.dmenurc"

if [[ $EUID -ne 0 ]]; then
    if ! gksudo -m "Enter sudo password for netcfg" echo "getting root privs"; then
        echo Bad Password
        exit 1
    fi
fi

choice="$(ls /etc/network.d -1Ap | grep -v \/ | $DMENU)"
if [[ "$choice" ]]; then
    sudo netcfg -a
    sudo netcfg "$choice"
fi
